### ISSUE TITLE
Erreur pour les communes de plus de 1000 inscrits.

### ISSUE THREAD

**Issue by olivierverdier** [LaSylv/resultats-elections-europeennes-france-2024#1]
Par exemple, à Paris, 2e arrondissement, [le site du ministère de l'intérieur](https://www.resultats-elections.interieur.gouv.fr/europeennes2024/ensemble_geographique/11/75/75102/index.html) indique **14 194** inscrits, alors que dans le fichier json il n'y en a que **14**. J'ai l'impression que c'est pareil dès qu'une commune a plus de mille inscrits?

Erreur à cause de l'espace entre les centaines et les milliers, peut-être?

**Comment by olivierverdier** [comment]
C'est le même problème pour les autres champs: `Abstentions`, `Votants`, etc.

**Comment by olivierverdier** [comment]
Possible solution: remplacer [cette ligne](https://github.com/LaSylv/resultats-elections-europeennes-france-2024/blob/ae66bb088f478989953dc1f6f2d03a237fb0ff30/extract-data.js#L81) par
```javascript
summaryData[key] = isNaN(parseFloat(value)) ? value : parseFloat(value.replace(',', '.').replace(" ",""));
```
Le caractère à remplacer n'est pas une espace, mais [une espace fine insécable](https://fr.wikipedia.org/wiki/Espace_ins%C3%A9cable#Espace_fine_ins%C3%A9cable).

**Comment by olivierverdier** [comment]
Et c'est le même problème avec la première table, donc le champs `count` est lui aussi affecté.

**Comment by LaSylv** [comment]
Merci pour le retour, je rpends en compte !

**Comment by LaSylv** [comment]
Fixé dans https://github.com/LaSylv/resultats-elections-europeennes-france-2024/commit/486d093ddedcbb67397586135dac682f3c451f2e !

**Comment by LaSylv** [comment]
Fixé
